### ISSUE TITLE
C:\Users\wollo\Downloads\Discord-Joiner-main\Discord-Joiner-main>py main.py   File "C:\Users\wollo\Downloads\Discord-Joiner-main\Discord-Joiner-main\main.py", line 115     match r.status_code:           ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ux6** [imvast/Discord-Joiner#5]
C:\Users\wollo\Downloads\Discord-Joiner-main\Discord-Joiner-main>py main.py
  File "C:\Users\wollo\Downloads\Discord-Joiner-main\Discord-Joiner-main\main.py", line 115
    match r.status_code:
          ^
SyntaxError: invalid syntax

**Comment by imvast** [comment]
skill issue noob python version
